# Site settings
title: Michael Large
email: m@codethebeard.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codethebeard.com" # the base hostname & protocol for your site
twitter_username: codethebeard
github_username:  codethebeard
linkedin_username:  codethebeard
codepen_username:  codethebeard

# Build settings
markdown: kramdown

# Post Settings
